class VocabularyEntry {
  const VocabularyEntry(
    this.english,
    this.czech,
    this.topic,
    this.page, {
    this.alternatives = const [],
  });

  final String english;
  final String czech;
  final String topic;
  final int page;
  final List<String> alternatives;

  bool accepts(String answer) {
    final normalized = normalizeAnswer(answer);
    return [
      english,
      ...alternatives,
    ].any((value) => normalizeAnswer(value) == normalized);
  }
}

String normalizeAnswer(String answer) => answer
    .trim()
    .toLowerCase()
    .replaceAll(RegExp('[’‘]'), "'")
    .replaceAll(RegExp(r'[.!?,]+$'), '')
    .replaceAll(RegExp(r'[-–]'), ' ')
    .replaceAll(RegExp(r'\s+'), ' ')
    .trim();

const vocabulary = <VocabularyEntry>[
  VocabularyEntry('friend', 'kamarád / kamarádka', 'Lidé a představování', 4),
  VocabularyEntry('new', 'nový', 'Lidé a představování', 4),
  VocabularyEntry('pet', 'domácí mazlíček', 'Lidé a představování', 4),
  VocabularyEntry('robot', 'robot', 'Lidé a představování', 4),
  VocabularyEntry(
    'competition',
    'soutěž',
    'Lidé a představování',
    4,
    alternatives: ['contest'],
  ),
  VocabularyEntry('prize', 'cena v soutěži', 'Lidé a představování', 4),
  VocabularyEntry('question', 'otázka', 'Lidé a představování', 4),
  VocabularyEntry('answer', 'odpověď', 'Lidé a představování', 4),
  VocabularyEntry('tablet', 'tablet', 'Lidé a představování', 4),
  VocabularyEntry('name', 'jméno', 'Lidé a představování', 4),
  VocabularyEntry('age', 'věk', 'Lidé a představování', 4),
  VocabularyEntry('ready', 'připravený', 'Lidé a představování', 4),
  VocabularyEntry(
    "What's your name?",
    'Jak se jmenuješ?',
    'Lidé a představování',
    4,
    alternatives: ['What is your name?'],
  ),
  VocabularyEntry(
    'How old are you?',
    'Kolik ti je let?',
    'Lidé a představování',
    4,
  ),
  VocabularyEntry(
    'Where are you from?',
    'Odkud jsi?',
    'Lidé a představování',
    4,
  ),
  VocabularyEntry(
    "I don't understand.",
    'Nerozumím.',
    'Lidé a představování',
    4,
    alternatives: ['I do not understand.'],
  ),
  VocabularyEntry(
    'Can you speak more slowly, please?',
    'Můžeš prosím mluvit pomaleji?',
    'Lidé a představování',
    4,
    alternatives: [
      'Can you please speak more slowly?',
      'Could you speak more slowly, please?',
    ],
  ),
  VocabularyEntry('birthday', 'narozeniny', 'Lidé a představování', 5),
  VocabularyEntry(
    'phone number',
    'telefonní číslo',
    'Lidé a představování',
    5,
    alternatives: ['telephone number'],
  ),
  VocabularyEntry('nationality', 'národnost', 'Lidé a představování', 5),
  VocabularyEntry('brother', 'bratr', 'Lidé a představování', 5),
  VocabularyEntry('sister', 'sestra', 'Lidé a představování', 5),
  VocabularyEntry('family', 'rodina', 'Lidé a představování', 5),
  VocabularyEntry(
    'classmate',
    'spolužák / spolužačka',
    'Lidé a představování',
    5,
  ),
  VocabularyEntry('cat', 'kočka', 'Lidé a představování', 5),
  VocabularyEntry('dog', 'pes', 'Lidé a představování', 5),
  VocabularyEntry(
    'favourite',
    'oblíbený',
    'Lidé a představování',
    5,
    alternatives: ['favorite'],
  ),
  VocabularyEntry('singer', 'zpěvák / zpěvačka', 'Lidé a představování', 5),
  VocabularyEntry(
    'Where do you live?',
    'Kde bydlíš?',
    'Lidé a představování',
    5,
  ),
  VocabularyEntry(
    "When's your birthday?",
    'Kdy máš narozeniny?',
    'Lidé a představování',
    5,
    alternatives: ['When is your birthday?'],
  ),
  VocabularyEntry(
    'Have you got any pets?',
    'Máš nějaké domácí mazlíčky?',
    'Lidé a představování',
    5,
    alternatives: ['Do you have any pets?'],
  ),

  VocabularyEntry('January', 'leden', 'Měsíce', 5),
  VocabularyEntry('February', 'únor', 'Měsíce', 5),
  VocabularyEntry('March', 'březen', 'Měsíce', 5),
  VocabularyEntry('April', 'duben', 'Měsíce', 5),
  VocabularyEntry('May', 'květen', 'Měsíce', 5),
  VocabularyEntry('June', 'červen', 'Měsíce', 5),
  VocabularyEntry('July', 'červenec', 'Měsíce', 5),
  VocabularyEntry('August', 'srpen', 'Měsíce', 5),
  VocabularyEntry('September', 'září', 'Měsíce', 5),
  VocabularyEntry('October', 'říjen', 'Měsíce', 5),
  VocabularyEntry('November', 'listopad', 'Měsíce', 5),
  VocabularyEntry('December', 'prosinec', 'Měsíce', 5),

  VocabularyEntry('first', 'první (slovem)', 'Čísla a data', 5),
  VocabularyEntry('second', 'druhý (slovem)', 'Čísla a data', 5),
  VocabularyEntry('third', 'třetí (slovem)', 'Čísla a data', 5),
  VocabularyEntry('fourth', 'čtvrtý (slovem)', 'Čísla a data', 5),
  VocabularyEntry('fifth', 'pátý (slovem)', 'Čísla a data', 5),
  VocabularyEntry('eleventh', 'jedenáctý (slovem)', 'Čísla a data', 5),
  VocabularyEntry('twentieth', 'dvacátý (slovem)', 'Čísla a data', 5),
  VocabularyEntry('twenty-second', 'dvacátý druhý (slovem)', 'Čísla a data', 5),
  VocabularyEntry('twenty-third', 'dvacátý třetí (slovem)', 'Čísla a data', 5),
  VocabularyEntry('twenty-eighth', 'dvacátý osmý (slovem)', 'Čísla a data', 5),
  VocabularyEntry('thirty-first', 'třicátý první (slovem)', 'Čísla a data', 5),
  VocabularyEntry('month', 'měsíc v kalendáři', 'Čísla a data', 5),
  VocabularyEntry('date', 'datum', 'Čísla a data', 5),

  VocabularyEntry(
    'UK',
    'Spojené království',
    'Země a národnosti',
    5,
    alternatives: ['the UK', 'United Kingdom', 'the United Kingdom'],
  ),
  VocabularyEntry('British', 'britský / Brit / Britka', 'Země a národnosti', 5),
  VocabularyEntry('Hungary', 'Maďarsko', 'Země a národnosti', 5),
  VocabularyEntry(
    'Hungarian',
    'maďarský / Maďar / Maďarka',
    'Země a národnosti',
    5,
  ),
  VocabularyEntry('France', 'Francie', 'Země a národnosti', 5),
  VocabularyEntry(
    'French',
    'francouzský / Francouz / Francouzka',
    'Země a národnosti',
    5,
  ),
  VocabularyEntry('Switzerland', 'Švýcarsko', 'Země a národnosti', 5),
  VocabularyEntry(
    'Swiss',
    'švýcarský / Švýcar / Švýcarka',
    'Země a národnosti',
    5,
  ),
  VocabularyEntry(
    'Czech Republic',
    'Česká republika',
    'Země a národnosti',
    5,
    alternatives: ['the Czech Republic', 'Czechia'],
  ),
  VocabularyEntry('Czech', 'český / Čech / Češka', 'Země a národnosti', 5),
  VocabularyEntry('Poland', 'Polsko', 'Země a národnosti', 5),
  VocabularyEntry('Polish', 'polský / Polák / Polka', 'Země a národnosti', 5),
  VocabularyEntry('Slovenia', 'Slovinsko', 'Země a národnosti', 5),
  VocabularyEntry(
    'Slovenian',
    'slovinský / Slovinec / Slovinka',
    'Země a národnosti',
    5,
    alternatives: ['Slovene'],
  ),
  VocabularyEntry('Spain', 'Španělsko', 'Země a národnosti', 5),
  VocabularyEntry(
    'Spanish',
    'španělský / Španěl / Španělka',
    'Země a národnosti',
    5,
  ),
  VocabularyEntry('Slovakia', 'Slovensko', 'Země a národnosti', 5),
  VocabularyEntry(
    'Slovak',
    'slovenský / Slovák / Slovenka',
    'Země a národnosti',
    5,
  ),
  VocabularyEntry('England', 'Anglie', 'Země a národnosti', 4),

  VocabularyEntry('school', 'škola', 'Ve škole', 6),
  VocabularyEntry('exchange student', 'výměnný student', 'Ve škole', 6),
  VocabularyEntry('playground', 'dětské hřiště', 'Ve škole', 6),
  VocabularyEntry('entrance', 'vchod', 'Ve škole', 6),
  VocabularyEntry('library', 'knihovna', 'Ve škole', 6),
  VocabularyEntry(
    'canteen',
    'školní jídelna',
    'Ve škole',
    6,
    alternatives: [
      'school canteen',
      'cafeteria',
      'school cafeteria',
      'dining room',
    ],
  ),
  VocabularyEntry(
    'gym',
    'tělocvična',
    'Ve škole',
    6,
    alternatives: ['gymnasium'],
  ),
  VocabularyEntry(
    'stairs',
    'schody',
    'Ve škole',
    6,
    alternatives: ['staircase'],
  ),
  VocabularyEntry(
    'assembly hall',
    'školní aula / shromažďovací sál',
    'Ve škole',
    6,
  ),
  VocabularyEntry('music room', 'učebna hudební výchovy', 'Ve škole', 6),
  VocabularyEntry('classroom', 'třída (místnost)', 'Ve škole', 6),
  VocabularyEntry(
    'staffroom',
    'sborovna',
    'Ve škole',
    6,
    alternatives: ['staff room', "teachers' room"],
  ),
  VocabularyEntry(
    'science lab',
    'přírodovědná laboratoř',
    'Ve škole',
    6,
    alternatives: ['science laboratory'],
  ),
  VocabularyEntry(
    'toilets',
    'toalety',
    'Ve škole',
    6,
    alternatives: ['restrooms', 'toilet', 'restroom'],
  ),
  VocabularyEntry(
    "Head's office",
    'ředitelna',
    'Ve škole',
    6,
    alternatives: [
      "headteacher's office",
      "head teacher's office",
      "principal's office",
    ],
  ),
  VocabularyEntry(
    'playing fields',
    'sportovní hřiště (množné číslo)',
    'Ve škole',
    6,
    alternatives: ['sports fields'],
  ),
  VocabularyEntry('ground floor', 'přízemí', 'Ve škole', 6),
  VocabularyEntry('first floor', 'první patro', 'Ve škole', 6),
  VocabularyEntry(
    'on the left',
    'vlevo',
    'Ve škole',
    6,
    alternatives: ['on your left', 'to the left', 'left'],
  ),
  VocabularyEntry(
    'on the right',
    'vpravo',
    'Ve škole',
    6,
    alternatives: ['on your right', 'to the right', 'right'],
  ),
  VocabularyEntry(
    'head teacher',
    'ředitel / ředitelka školy',
    'Ve škole',
    7,
    alternatives: ['headteacher', 'principal', 'headmaster', 'headmistress'],
  ),
  VocabularyEntry(
    'secondary school',
    'škola pro starší žáky (britská)',
    'Ve škole',
    7,
  ),
  VocabularyEntry(
    'PE',
    'tělesná výchova',
    'Ve škole',
    7,
    alternatives: ['physical education', 'P.E.'],
  ),
  VocabularyEntry(
    'dining room',
    'jídelna',
    'Ve škole',
    7,
    alternatives: ['canteen', 'cafeteria'],
  ),
  VocabularyEntry('bell', 'zvonek', 'Ve škole', 7),
  VocabularyEntry('lunch', 'oběd', 'Ve škole', 7),
  VocabularyEntry('food', 'jídlo', 'Ve škole', 7),

  VocabularyEntry(
    'wait a minute',
    'počkej chvilku',
    'Činnosti a fráze',
    4,
    alternatives: ['wait a moment'],
  ),
  VocabularyEntry('speak', 'mluvit', 'Činnosti a fráze', 4),
  VocabularyEntry('slowly', 'pomalu', 'Činnosti a fráze', 4),
  VocabularyEntry('please', 'prosím (při žádosti)', 'Činnosti a fráze', 4),
  VocabularyEntry('save', 'uložit', 'Činnosti a fráze', 4),
  VocabularyEntry('send', 'poslat / odeslat', 'Činnosti a fráze', 4),
  VocabularyEntry('close', 'zavřít', 'Činnosti a fráze', 4),
  VocabularyEntry('hurry up', 'pospěš si', 'Činnosti a fráze', 4),
  VocabularyEntry('again', 'znovu', 'Činnosti a fráze', 4),
  VocabularyEntry(
    'half past eight',
    'půl deváté (slovem)',
    'Činnosti a fráze',
    4,
    alternatives: ['eight thirty'],
  ),
  VocabularyEntry(
    "twelve o'clock",
    'dvanáct hodin (slovem)',
    'Činnosti a fráze',
    4,
  ),
  VocabularyEntry('Good morning.', 'Dobré ráno.', 'Činnosti a fráze', 7),
  VocabularyEntry(
    'Welcome to our school.',
    'Vítejte v naší škole.',
    'Činnosti a fráze',
    7,
  ),
  VocabularyEntry(
    'Pleased to meet you.',
    'Těší mě.',
    'Činnosti a fráze',
    7,
    alternatives: ['Nice to meet you.'],
  ),
  VocabularyEntry('introduce', 'představit někoho', 'Činnosti a fráze', 7),
  VocabularyEntry('show', 'ukázat', 'Činnosti a fráze', 7),
  VocabularyEntry('Come on!', 'Pojď! / Tak pojď!', 'Činnosti a fráze', 7),
  VocabularyEntry('concert', 'koncert', 'Činnosti a fráze', 7),
  VocabularyEntry('tomorrow', 'zítra', 'Činnosti a fráze', 7),
  VocabularyEntry('traditional', 'tradiční', 'Činnosti a fráze', 7),
  VocabularyEntry('jazz', 'jazz', 'Činnosti a fráze', 7),
  VocabularyEntry(
    'brilliant',
    'skvělý',
    'Činnosti a fráze',
    7,
    alternatives: ['great', 'excellent', 'fantastic'],
  ),
  VocabularyEntry('basketball', 'basketbal', 'Činnosti a fráze', 7),
  VocabularyEntry(
    'football',
    'fotbal',
    'Činnosti a fráze',
    7,
    alternatives: ['soccer'],
  ),
  VocabularyEntry('gymnastics', 'gymnastika', 'Činnosti a fráze', 7),
  VocabularyEntry('It depends.', 'To záleží.', 'Činnosti a fráze', 7),
  VocabularyEntry(
    'demonstration',
    'ukázka / předvedení',
    'Činnosti a fráze',
    7,
    alternatives: ['display'],
  ),
  VocabularyEntry('visitor', 'návštěvník / návštěvnice', 'Činnosti a fráze', 7),
  VocabularyEntry(
    'sports clothes',
    'sportovní oblečení',
    'Činnosti a fráze',
    7,
    alternatives: ['sportswear', 'sport clothes'],
  ),
  VocabularyEntry('museum', 'muzeum', 'Činnosti a fráze', 7),
  VocabularyEntry(
    'Only joking.',
    'Jen žertuji.',
    'Činnosti a fráze',
    7,
    alternatives: [
      'Just joking.',
      'Just kidding.',
      "I'm only joking.",
      'I am only joking.',
    ],
  ),
  VocabularyEntry('always', 'vždy', 'Činnosti a fráze', 7),
  VocabularyEntry('usually', 'obvykle', 'Činnosti a fráze', 7),
  VocabularyEntry('often', 'často', 'Činnosti a fráze', 7),
  VocabularyEntry('sometimes', 'někdy', 'Činnosti a fráze', 7),
  VocabularyEntry('never', 'nikdy', 'Činnosti a fráze', 7),
];
