import 'package:aaaskola/vocabulary.dart';

const vocabularyGrade5 = <VocabularyEntry>[
  VocabularyEntry('pencil', 'tužka', 'Školní potřeby', 4),
  VocabularyEntry(
    'rubber',
    'guma na gumování',
    'Školní potřeby',
    4,
    alternatives: ['eraser'],
  ),
  VocabularyEntry('ruler', 'pravítko', 'Školní potřeby', 4),
  VocabularyEntry(
    'sharpener',
    'ořezávátko',
    'Školní potřeby',
    4,
    alternatives: ['pencil sharpener'],
  ),
  VocabularyEntry('pen', 'pero / propiska', 'Školní potřeby', 4),
  VocabularyEntry(
    'crayon',
    'voskovka',
    'Školní potřeby',
    4,
    alternatives: ['wax crayon'],
  ),
  VocabularyEntry(
    'notebook',
    'sešit',
    'Školní potřeby',
    4,
    alternatives: ['exercise book'],
  ),
  VocabularyEntry('book', 'kniha', 'Školní potřeby', 4),
  VocabularyEntry(
    'scissors',
    'nůžky',
    'Školní potřeby',
    4,
    alternatives: ['a pair of scissors'],
  ),
  VocabularyEntry('calculator', 'kalkulačka', 'Školní potřeby', 4),
  VocabularyEntry('pencil case', 'penál', 'Školní potřeby', 4),
  VocabularyEntry(
    'school bag',
    'školní taška',
    'Školní potřeby',
    4,
    alternatives: ['schoolbag', 'school backpack'],
  ),
  VocabularyEntry('snake', 'had', 'Zvířata a věci', 4),
  VocabularyEntry('cage', 'klec', 'Zvířata a věci', 4),
  VocabularyEntry('chameleon', 'chameleon', 'Zvířata a věci', 5),
  VocabularyEntry('red', 'červená', 'Barvy', 5),
  VocabularyEntry('orange', 'oranžová', 'Barvy', 5),
  VocabularyEntry('yellow', 'žlutá', 'Barvy', 5),
  VocabularyEntry('light green', 'světle zelená', 'Barvy', 5),
  VocabularyEntry('dark green', 'tmavě zelená', 'Barvy', 5),
  VocabularyEntry('light blue', 'světle modrá', 'Barvy', 5),
  VocabularyEntry('dark blue', 'tmavě modrá', 'Barvy', 5),
  VocabularyEntry('purple', 'fialová', 'Barvy', 5, alternatives: ['violet']),
  VocabularyEntry('black', 'černá', 'Barvy', 5),
  VocabularyEntry('white', 'bílá', 'Barvy', 5),
  VocabularyEntry('grey', 'šedá', 'Barvy', 5, alternatives: ['gray']),
  VocabularyEntry('brown', 'hnědá', 'Barvy', 5),
  VocabularyEntry('pink', 'růžová', 'Barvy', 5),
  VocabularyEntry('blue', 'modrá', 'Barvy', 5),
  VocabularyEntry('green', 'zelená', 'Barvy', 14),
  VocabularyEntry('colour', 'barva', 'Barvy', 5, alternatives: ['color']),
  VocabularyEntry('read', 'číst', 'Pokyny a slovesa', 5),
  VocabularyEntry('listen', 'poslouchat', 'Pokyny a slovesa', 5),
  VocabularyEntry('match', 'přiřadit / spojit dvojice', 'Pokyny a slovesa', 5),
  VocabularyEntry('work', 'pracovat', 'Pokyny a slovesa', 5),
  VocabularyEntry('find', 'najít', 'Pokyny a slovesa', 5),
  VocabularyEntry(
    'complete',
    'doplnit / dokončit',
    'Pokyny a slovesa',
    5,
    alternatives: ['finish'],
  ),
  VocabularyEntry('play', 'hrát', 'Pokyny a slovesa', 5),
  VocabularyEntry('check', 'zkontrolovat', 'Pokyny a slovesa', 5),
  VocabularyEntry('repeat', 'opakovat', 'Pokyny a slovesa', 5),
  VocabularyEntry('write', 'psát', 'Pokyny a slovesa', 5),
  VocabularyEntry('guess', 'hádat', 'Pokyny a slovesa', 5),
  VocabularyEntry('one', 'jedna (1)', 'Čísla', 6),
  VocabularyEntry('two', 'dva (2)', 'Čísla', 6),
  VocabularyEntry('three', 'tři (3)', 'Čísla', 6),
  VocabularyEntry('four', 'čtyři (4)', 'Čísla', 6),
  VocabularyEntry('five', 'pět (5)', 'Čísla', 6),
  VocabularyEntry('six', 'šest (6)', 'Čísla', 6),
  VocabularyEntry('seven', 'sedm (7)', 'Čísla', 6),
  VocabularyEntry('eight', 'osm (8)', 'Čísla', 6),
  VocabularyEntry('nine', 'devět (9)', 'Čísla', 6),
  VocabularyEntry('ten', 'deset (10)', 'Čísla', 6),
  VocabularyEntry('eleven', 'jedenáct (11)', 'Čísla', 6),
  VocabularyEntry('twelve', 'dvanáct (12)', 'Čísla', 6),
  VocabularyEntry('thirteen', 'třináct (13)', 'Čísla', 6),
  VocabularyEntry('fourteen', 'čtrnáct (14)', 'Čísla', 6),
  VocabularyEntry('fifteen', 'patnáct (15)', 'Čísla', 6),
  VocabularyEntry('sixteen', 'šestnáct (16)', 'Čísla', 6),
  VocabularyEntry('seventeen', 'sedmnáct (17)', 'Čísla', 6),
  VocabularyEntry('eighteen', 'osmnáct (18)', 'Čísla', 6),
  VocabularyEntry('nineteen', 'devatenáct (19)', 'Čísla', 6),
  VocabularyEntry('twenty', 'dvacet (20)', 'Čísla', 6),
  VocabularyEntry('thirty', 'třicet (30)', 'Čísla', 12),
  VocabularyEntry('forty', 'čtyřicet (40)', 'Čísla', 12),
  VocabularyEntry('fifty', 'padesát (50)', 'Čísla', 12),
  VocabularyEntry('sixty', 'šedesát (60)', 'Čísla', 12),
  VocabularyEntry('seventy', 'sedmdesát (70)', 'Čísla', 12),
  VocabularyEntry('eighty', 'osmdesát (80)', 'Čísla', 12),
  VocabularyEntry('ninety', 'devadesát (90)', 'Čísla', 12),
  VocabularyEntry(
    'one hundred',
    'sto (100)',
    'Čísla',
    12,
    alternatives: ['a hundred'],
  ),
  VocabularyEntry('friend', 'kamarád / kamarádka', 'Lidé a představování', 6),
  VocabularyEntry('name', 'jméno', 'Lidé a představování', 6),
  VocabularyEntry('age', 'věk', 'Lidé a představování', 7),
  VocabularyEntry(
    'favourite',
    'oblíbený',
    'Lidé a představování',
    6,
    alternatives: ['favorite'],
  ),
  VocabularyEntry(
    'film',
    'film',
    'Lidé a představování',
    6,
    alternatives: ['movie'],
  ),
  VocabularyEntry('character', 'postava v příběhu', 'Lidé a představování', 6),
  VocabularyEntry(
    'phone number',
    'telefonní číslo',
    'Lidé a představování',
    6,
    alternatives: ['telephone number'],
  ),
  VocabularyEntry('bus', 'autobus', 'Místa a doprava', 6),
  VocabularyEntry('school', 'škola', 'Místa a doprava', 6),
  VocabularyEntry('England', 'Anglie', 'Země a národnosti', 7),
  VocabularyEntry('English', 'anglický / angličtina', 'Země a národnosti', 7),
  VocabularyEntry('Scotland', 'Skotsko', 'Země a národnosti', 7),
  VocabularyEntry('Scottish', 'skotský', 'Země a národnosti', 7),
  VocabularyEntry('Ireland', 'Irsko', 'Země a národnosti', 7),
  VocabularyEntry('Irish', 'irský', 'Země a národnosti', 7),
  VocabularyEntry('Wales', 'Wales', 'Země a národnosti', 7),
  VocabularyEntry('Welsh', 'velšský', 'Země a národnosti', 7),
  VocabularyEntry('Hungary', 'Maďarsko', 'Země a národnosti', 7),
  VocabularyEntry('Hungarian', 'maďarský', 'Země a národnosti', 7),
  VocabularyEntry('Croatia', 'Chorvatsko', 'Země a národnosti', 7),
  VocabularyEntry('Croatian', 'chorvatský', 'Země a národnosti', 7),
  VocabularyEntry('Serbia', 'Srbsko', 'Země a národnosti', 7),
  VocabularyEntry('Serbian', 'srbský', 'Země a národnosti', 7),
  VocabularyEntry('Slovenia', 'Slovinsko', 'Země a národnosti', 7),
  VocabularyEntry(
    'Slovenian',
    'slovinský',
    'Země a národnosti',
    7,
    alternatives: ['Slovene'],
  ),
  VocabularyEntry(
    'the Czech Republic',
    'Česká republika',
    'Země a národnosti',
    7,
    alternatives: ['Czech Republic', 'Czechia'],
  ),
  VocabularyEntry('Czech', 'český / čeština', 'Země a národnosti', 7),
  VocabularyEntry('China', 'Čína', 'Země a národnosti', 7),
  VocabularyEntry('Chinese', 'čínský / čínština', 'Země a národnosti', 7),
  VocabularyEntry('Spain', 'Španělsko', 'Země a národnosti', 7),
  VocabularyEntry('Spanish', 'španělský / španělština', 'Země a národnosti', 7),
  VocabularyEntry('India', 'Indie', 'Země a národnosti', 7),
  VocabularyEntry('Indian', 'indický', 'Země a národnosti', 7),
  VocabularyEntry('Poland', 'Polsko', 'Země a národnosti', 7),
  VocabularyEntry('Polish', 'polský', 'Země a národnosti', 6),
  VocabularyEntry('play basketball', 'hrát basketbal', 'Činnosti', 8),
  VocabularyEntry('spell', 'hláskovat', 'Činnosti', 8),
  VocabularyEntry(
    'play football',
    'hrát fotbal',
    'Činnosti',
    8,
    alternatives: ['play soccer'],
  ),
  VocabularyEntry('run', 'běhat', 'Činnosti', 8),
  VocabularyEntry(
    'play the guitar',
    'hrát na kytaru',
    'Činnosti',
    8,
    alternatives: ['play guitar'],
  ),
  VocabularyEntry(
    'ride a bike',
    'jezdit na kole',
    'Činnosti',
    8,
    alternatives: ['ride a bicycle', 'cycle'],
  ),
  VocabularyEntry(
    'climb a tree',
    'lézt na strom',
    'Činnosti',
    8,
    alternatives: ['climb trees'],
  ),
  VocabularyEntry('walk', 'chodit / jít pěšky', 'Činnosti', 8),
  VocabularyEntry('draw', 'kreslit', 'Činnosti', 8),
  VocabularyEntry('speak Chinese', 'mluvit čínsky', 'Činnosti', 8),
  VocabularyEntry(
    'rollerblade',
    'jezdit na kolečkových bruslích',
    'Činnosti',
    8,
    alternatives: ['roller skate', 'inline skate'],
  ),
  VocabularyEntry('swim', 'plavat', 'Činnosti', 8),
  VocabularyEntry('sing', 'zpívat', 'Činnosti', 8),
  VocabularyEntry('park', 'park', 'Místa a doprava', 8),
  VocabularyEntry('wheelchair', 'invalidní vozík', 'Místa a doprava', 8),
  VocabularyEntry('leg', 'noha', 'Zvířata a věci', 8),
  VocabularyEntry('broken', 'zlomený', 'Popis lidí a věcí', 8),
  VocabularyEntry(
    'fast',
    'rychlý',
    'Popis lidí a věcí',
    8,
    alternatives: ['quick'],
  ),
  VocabularyEntry('game', 'hra', 'Zvířata a věci', 8),
  VocabularyEntry('alphabet', 'abeceda', 'Ve třídě', 9),
  VocabularyEntry('letter', 'písmeno', 'Ve třídě', 9),
  VocabularyEntry('word', 'slovo', 'Ve třídě', 9),
  VocabularyEntry('page', 'stránka v knize', 'Ve třídě', 9),
  VocabularyEntry('robot', 'robot', 'Zvířata a věci', 9),
  VocabularyEntry(
    'scared',
    'vystrašený',
    'Pocity',
    10,
    alternatives: ['frightened', 'afraid'],
  ),
  VocabularyEntry('angry', 'rozzlobený', 'Pocity', 10),
  VocabularyEntry('tired', 'unavený', 'Pocity', 10),
  VocabularyEntry('hungry', 'hladový', 'Pocity', 10),
  VocabularyEntry(
    'excited',
    'nadšený',
    'Pocity',
    10,
    alternatives: ['enthusiastic'],
  ),
  VocabularyEntry('sad', 'smutný', 'Pocity', 10),
  VocabularyEntry('cold', 'je mu zima (jedním slovem)', 'Pocity', 10),
  VocabularyEntry('happy', 'šťastný', 'Pocity', 10),
  VocabularyEntry('bored', 'znuděný', 'Pocity', 10),
  VocabularyEntry('hot', 'je mu horko (jedním slovem)', 'Pocity', 10),
  VocabularyEntry('thirsty', 'žíznivý', 'Pocity', 10),
  VocabularyEntry('sleepy', 'ospalý', 'Pocity', 10),
  VocabularyEntry(
    'playground',
    'dětské / školní hřiště',
    'Místa a doprava',
    10,
  ),
  VocabularyEntry('teacher', 'učitel / učitelka', 'Ve třídě', 11),
  VocabularyEntry(
    'student',
    'žák / žákyně',
    'Ve třídě',
    11,
    alternatives: ['pupil'],
  ),
  VocabularyEntry('true', 'pravdivý', 'Ve třídě', 11),
  VocabularyEntry('false', 'nepravdivý', 'Ve třídě', 11),
  VocabularyEntry('person', 'osoba', 'Lidé a představování', 11),
  VocabularyEntry('thing', 'věc', 'Zvířata a věci', 11),
  VocabularyEntry(
    'grandmother',
    'babička',
    'Rodina',
    12,
    alternatives: ['grandma', 'granny', 'gran'],
  ),
  VocabularyEntry(
    'grandfather',
    'dědeček',
    'Rodina',
    12,
    alternatives: ['grandpa', 'grandad', 'granddad'],
  ),
  VocabularyEntry(
    'mother',
    'matka / maminka',
    'Rodina',
    12,
    alternatives: ['mum', 'mom', 'mummy', 'mommy'],
  ),
  VocabularyEntry(
    'father',
    'otec / tatínek',
    'Rodina',
    12,
    alternatives: ['dad', 'daddy'],
  ),
  VocabularyEntry(
    'aunt',
    'teta',
    'Rodina',
    12,
    alternatives: ['auntie', 'aunty'],
  ),
  VocabularyEntry('uncle', 'strýc', 'Rodina', 12),
  VocabularyEntry('brother', 'bratr', 'Rodina', 12),
  VocabularyEntry('sister', 'sestra', 'Rodina', 12),
  VocabularyEntry('cousin', 'bratranec / sestřenice', 'Rodina', 18),
  VocabularyEntry('family', 'rodina', 'Rodina', 12),
  VocabularyEntry('twins', 'dvojčata', 'Rodina', 12),
  VocabularyEntry('grandparents', 'prarodiče', 'Rodina', 12),
  VocabularyEntry('baby', 'miminko', 'Rodina', 12),
  VocabularyEntry('tall', 'vysoký (člověk)', 'Popis lidí a věcí', 12),
  VocabularyEntry('strong', 'silný', 'Popis lidí a věcí', 12),
  VocabularyEntry('short', 'malý vzrůstem / nízký', 'Popis lidí a věcí', 12),
  VocabularyEntry(
    'pretty',
    'hezký / hezká',
    'Popis lidí a věcí',
    12,
    alternatives: ['beautiful', 'good-looking'],
  ),
  VocabularyEntry(
    'clever',
    'chytrý',
    'Popis lidí a věcí',
    12,
    alternatives: ['smart', 'intelligent'],
  ),
  VocabularyEntry('young', 'mladý', 'Popis lidí a věcí', 12),
  VocabularyEntry('old', 'starý', 'Popis lidí a věcí', 12),
  VocabularyEntry(
    'nice',
    'milý',
    'Popis lidí a věcí',
    12,
    alternatives: ['kind'],
  ),
  VocabularyEntry(
    'identical',
    'totožný / úplně stejný',
    'Popis lidí a věcí',
    12,
  ),
  VocabularyEntry(
    'fair',
    'světlovlasý',
    'Popis lidí a věcí',
    13,
    alternatives: ['fair-haired', 'blond', 'blonde'],
  ),
  VocabularyEntry('animal', 'zvíře', 'Zvířata a věci', 12),
  VocabularyEntry(
    'photo',
    'fotografie',
    'Zvířata a věci',
    13,
    alternatives: ['photograph'],
  ),
  VocabularyEntry('family tree', 'rodokmen', 'Rodina', 13),
  VocabularyEntry('I', 'já', 'Zájmena', 15),
  VocabularyEntry('you', 'ty / vy', 'Zájmena', 13),
  VocabularyEntry('he', 'on', 'Zájmena', 11),
  VocabularyEntry('she', 'ona', 'Zájmena', 11),
  VocabularyEntry('it', 'ono / to', 'Zájmena', 15),
  VocabularyEntry('we', 'my', 'Zájmena', 13),
  VocabularyEntry('they', 'oni / ony', 'Zájmena', 13),
  VocabularyEntry('my', 'můj / moje', 'Zájmena', 15),
  VocabularyEntry('your', 'tvůj / váš', 'Zájmena', 15),
  VocabularyEntry('his', 'jeho (patří muži nebo chlapci)', 'Zájmena', 15),
  VocabularyEntry('her', 'její', 'Zájmena', 15),
  VocabularyEntry('its', 'jeho (patří věci nebo zvířeti)', 'Zájmena', 15),
  VocabularyEntry('our', 'náš / naše', 'Zájmena', 15),
  VocabularyEntry('their', 'jejich', 'Zájmena', 15),
  VocabularyEntry('birthday', 'narozeniny', 'Narozeniny a měsíce', 14),
  VocabularyEntry('cake', 'dort', 'Narozeniny a měsíce', 14),
  VocabularyEntry(
    'present',
    'dárek',
    'Narozeniny a měsíce',
    14,
    alternatives: ['gift'],
  ),
  VocabularyEntry('decorations', 'ozdoby', 'Narozeniny a měsíce', 14),
  VocabularyEntry('kitchen', 'kuchyně', 'Místa a doprava', 14),
  VocabularyEntry('door', 'dveře', 'Zvířata a věci', 14),
  VocabularyEntry(
    'tummy',
    'bříško',
    'Zvířata a věci',
    14,
    alternatives: ['belly', 'stomach'],
  ),
  VocabularyEntry(
    'spotty',
    'puntíkovaný / skvrnitý',
    'Popis lidí a věcí',
    14,
    alternatives: ['spotted', 'dotted'],
  ),
  VocabularyEntry('children', 'děti', 'Rodina', 14, alternatives: ['kids']),
  VocabularyEntry('follow', 'následovat', 'Pokyny a slovesa', 14),
  VocabularyEntry('need', 'potřebovat', 'Pokyny a slovesa', 14),
  VocabularyEntry('think', 'myslet', 'Pokyny a slovesa', 14),
  VocabularyEntry('January', 'leden', 'Narozeniny a měsíce', 15),
  VocabularyEntry('February', 'únor', 'Narozeniny a měsíce', 15),
  VocabularyEntry('March', 'březen', 'Narozeniny a měsíce', 15),
  VocabularyEntry('April', 'duben', 'Narozeniny a měsíce', 15),
  VocabularyEntry('May', 'květen', 'Narozeniny a měsíce', 15),
  VocabularyEntry('June', 'červen', 'Narozeniny a měsíce', 15),
  VocabularyEntry('July', 'červenec', 'Narozeniny a měsíce', 15),
  VocabularyEntry('August', 'srpen', 'Narozeniny a měsíce', 15),
  VocabularyEntry('September', 'září', 'Narozeniny a měsíce', 15),
  VocabularyEntry('October', 'říjen', 'Narozeniny a měsíce', 15),
  VocabularyEntry('November', 'listopad', 'Narozeniny a měsíce', 15),
  VocabularyEntry('December', 'prosinec', 'Narozeniny a měsíce', 15),
  VocabularyEntry('month', 'měsíc (v kalendáři)', 'Narozeniny a měsíce', 15),
  VocabularyEntry('first', 'první (1.)', 'Řadové číslovky', 15),
  VocabularyEntry('second', 'druhý (2.)', 'Řadové číslovky', 15),
  VocabularyEntry('third', 'třetí (3.)', 'Řadové číslovky', 15),
  VocabularyEntry('fourth', 'čtvrtý (4.)', 'Řadové číslovky', 15),
  VocabularyEntry('fifth', 'pátý (5.)', 'Řadové číslovky', 15),
  VocabularyEntry('twentieth', 'dvacátý (20.)', 'Řadové číslovky', 15),
  VocabularyEntry('twenty-first', 'dvacátý první (21.)', 'Řadové číslovky', 15),
  VocabularyEntry(
    'twenty-second',
    'dvacátý druhý (22.)',
    'Řadové číslovky',
    15,
  ),
  VocabularyEntry('twenty-third', 'dvacátý třetí (23.)', 'Řadové číslovky', 15),
  VocabularyEntry('twenty-sixth', 'dvacátý šestý (26.)', 'Řadové číslovky', 15),
  VocabularyEntry(
    'twenty-seventh',
    'dvacátý sedmý (27.)',
    'Řadové číslovky',
    15,
  ),
  VocabularyEntry('thirty-first', 'třicátý první (31.)', 'Řadové číslovky', 15),
  VocabularyEntry('Art', 'výtvarná výchova', 'Školní předměty', 16),
  VocabularyEntry('History', 'dějepis', 'Školní předměty', 16),
  VocabularyEntry(
    'Maths',
    'matematika',
    'Školní předměty',
    16,
    alternatives: ['math', 'mathematics'],
  ),
  VocabularyEntry('Music', 'hudební výchova / hudba', 'Školní předměty', 16),
  VocabularyEntry(
    'PE',
    'tělesná výchova / tělocvik',
    'Školní předměty',
    16,
    alternatives: ['physical education', 'P.E.', 'P.E'],
  ),
  VocabularyEntry(
    'Science',
    'přírodní vědy (školní předmět)',
    'Školní předměty',
    16,
  ),
  VocabularyEntry('Technology', 'technická výchova', 'Školní předměty', 16),
  VocabularyEntry('Biology', 'biologie / přírodopis', 'Školní předměty', 17),
  VocabularyEntry(
    'subject',
    'školní předmět',
    'Ve třídě',
    16,
    alternatives: ['school subject'],
  ),
  VocabularyEntry(
    'timetable',
    'rozvrh hodin',
    'Ve třídě',
    16,
    alternatives: ['schedule', 'school timetable'],
  ),
  VocabularyEntry('gymnastics', 'gymnastika', 'Činnosti', 16),
  VocabularyEntry(
    'football training',
    'fotbalový trénink',
    'Činnosti',
    16,
    alternatives: ['football practice', 'soccer practice', 'soccer training'],
  ),
  VocabularyEntry(
    'kit',
    'sportovní výbava',
    'Zvířata a věci',
    16,
    alternatives: ['sports kit', 'sports equipment'],
  ),
  VocabularyEntry(
    'trainer',
    'trenér',
    'Lidé a představování',
    16,
    alternatives: ['coach'],
  ),
  VocabularyEntry('ready', 'připravený', 'Popis lidí a věcí', 16),
  VocabularyEntry('late', 'pozdě', 'Dny a čas', 16),
  VocabularyEntry(
    'nearly',
    'téměř / skoro',
    'Dny a čas',
    16,
    alternatives: ['almost'],
  ),
  VocabularyEntry('today', 'dnes', 'Dny a čas', 15),
  VocabularyEntry('tomorrow', 'zítra', 'Dny a čas', 16),
  VocabularyEntry('soon', 'brzy', 'Dny a čas', 15),
  VocabularyEntry('Monday', 'pondělí', 'Dny a čas', 17),
  VocabularyEntry('Tuesday', 'úterý', 'Dny a čas', 17),
  VocabularyEntry('Wednesday', 'středa', 'Dny a čas', 17),
  VocabularyEntry('Thursday', 'čtvrtek', 'Dny a čas', 17),
  VocabularyEntry('Friday', 'pátek', 'Dny a čas', 17),
  VocabularyEntry('Saturday', 'sobota', 'Dny a čas', 17),
  VocabularyEntry('Sunday', 'neděle', 'Dny a čas', 17),
  VocabularyEntry('day', 'den', 'Dny a čas', 17),
  VocabularyEntry('week', 'týden', 'Dny a čas', 17),
  VocabularyEntry(
    "three o'clock",
    'tři hodiny (3:00, napiš slovy)',
    'Kolik je hodin?',
    17,
    alternatives: ['three', 'three oclock'],
  ),
  VocabularyEntry(
    'five past three',
    'pět minut po třetí (3:05, napiš slovy)',
    'Kolik je hodin?',
    17,
    alternatives: ['three oh five', 'three zero five'],
  ),
  VocabularyEntry(
    'quarter past three',
    'čtvrt na čtyři (3:15, napiš slovy)',
    'Kolik je hodin?',
    17,
    alternatives: ['a quarter past three', 'three fifteen'],
  ),
  VocabularyEntry(
    'half past three',
    'půl čtvrté (3:30, napiš slovy)',
    'Kolik je hodin?',
    17,
    alternatives: ['three thirty'],
  ),
  VocabularyEntry(
    'twenty-five to four',
    'za dvacet pět minut čtyři (3:35, napiš slovy)',
    'Kolik je hodin?',
    17,
    alternatives: ['three thirty-five'],
  ),
  VocabularyEntry(
    'quarter to four',
    'tři čtvrtě na čtyři (3:45, napiš slovy)',
    'Kolik je hodin?',
    17,
    alternatives: ['a quarter to four', 'three forty-five'],
  ),
  VocabularyEntry(
    'five to four',
    'za pět minut čtyři (3:55, napiš slovy)',
    'Kolik je hodin?',
    17,
    alternatives: ['three fifty-five'],
  ),
  VocabularyEntry(
    'half past ten',
    'půl jedenácté (10:30, napiš slovy)',
    'Kolik je hodin?',
    17,
    alternatives: ['ten thirty'],
  ),
  VocabularyEntry(
    'quarter to eleven',
    'tři čtvrtě na jedenáct (10:45, napiš slovy)',
    'Kolik je hodin?',
    17,
    alternatives: ['a quarter to eleven', 'ten forty-five'],
  ),
  VocabularyEntry('lunch', 'oběd', 'Zvířata a věci', 17),
  VocabularyEntry('chess', 'šachy', 'Činnosti', 17),
  VocabularyEntry('break', 'přestávka', 'Ve třídě', 18),
  VocabularyEntry(
    'lesson',
    'vyučovací hodina',
    'Ve třídě',
    18,
    alternatives: ['class'],
  ),
  VocabularyEntry('feelings', 'pocity', 'Pocity', 19),
  VocabularyEntry('school bus', 'školní autobus', 'Místa a doprava', 19),
  VocabularyEntry('drama club', 'dramatický kroužek', 'Činnosti', 19),
  VocabularyEntry('supermarket', 'supermarket', 'Místa a doprava', 19),
  VocabularyEntry('bed', 'postel', 'Zvířata a věci', 19),
  VocabularyEntry(
    'the UK',
    'Spojené království',
    'Země a národnosti',
    20,
    alternatives: ['UK', 'United Kingdom', 'the United Kingdom'],
  ),
  VocabularyEntry(
    'the USA',
    'Spojené státy americké',
    'Země a národnosti',
    20,
    alternatives: [
      'USA',
      'US',
      'the US',
      'United States',
      'the United States',
      'United States of America',
      'the United States of America',
    ],
  ),
  VocabularyEntry('Canada', 'Kanada', 'Země a národnosti', 20),
  VocabularyEntry(
    'South Africa',
    'Jihoafrická republika',
    'Země a národnosti',
    20,
  ),
  VocabularyEntry('Australia', 'Austrálie', 'Země a národnosti', 20),
  VocabularyEntry('New Zealand', 'Nový Zéland', 'Země a národnosti', 20),
  VocabularyEntry('Jamaica', 'Jamajka', 'Země a národnosti', 20),
  VocabularyEntry('Singapore', 'Singapur', 'Země a národnosti', 20),
  VocabularyEntry('Jamaican', 'jamajský', 'Země a národnosti', 20),
  VocabularyEntry('Canadian', 'kanadský', 'Země a národnosti', 20),
  VocabularyEntry('Australian', 'australský', 'Země a národnosti', 20),
  VocabularyEntry('American', 'americký', 'Země a národnosti', 20),
  VocabularyEntry('Singaporean', 'singapurský', 'Země a národnosti', 20),
  VocabularyEntry('South African', 'jihoafrický', 'Země a národnosti', 20),
  VocabularyEntry(
    'French',
    'francouzský / francouzština',
    'Země a národnosti',
    20,
  ),
  VocabularyEntry('country', 'země / stát', 'Země a národnosti', 20),
  VocabularyEntry('language', 'jazyk (řeč)', 'Země a národnosti', 20),
  VocabularyEntry('flag', 'vlajka', 'Příroda a svět kolem nás', 20),
  VocabularyEntry('cross', 'kříž', 'Příroda a svět kolem nás', 20),
  VocabularyEntry('star', 'hvězda', 'Příroda a svět kolem nás', 20),
  VocabularyEntry('leaf', 'list stromu', 'Příroda a svět kolem nás', 20),
  VocabularyEntry('moon', 'měsíc (na obloze)', 'Příroda a svět kolem nás', 20),
  VocabularyEntry('map', 'mapa', 'Příroda a svět kolem nás', 20),
  VocabularyEntry('sundial', 'sluneční hodiny', 'Příroda a svět kolem nás', 21),
  VocabularyEntry('shadow', 'stín', 'Příroda a svět kolem nás', 21),
  VocabularyEntry('stick', 'klacek / hůl', 'Příroda a svět kolem nás', 21),
  VocabularyEntry('stones', 'kameny', 'Příroda a svět kolem nás', 21),
  VocabularyEntry('chalk', 'křída', 'Příroda a svět kolem nás', 21),
  VocabularyEntry(
    'watch',
    'náramkové hodinky',
    'Příroda a svět kolem nás',
    21,
    alternatives: ['wristwatch'],
  ),
  VocabularyEntry(
    'bucket',
    'kbelík',
    'Příroda a svět kolem nás',
    21,
    alternatives: ['pail'],
  ),
  VocabularyEntry('garden', 'zahrada', 'Příroda a svět kolem nás', 21),
  VocabularyEntry('city', 'velké město', 'Místa a doprava', 21),
  VocabularyEntry('house', 'dům', 'Místa a doprava', 21),
  VocabularyEntry('morning', 'ráno / dopoledne', 'Dny a čas', 21),
  VocabularyEntry('night', 'noc', 'Dny a čas', 21),
  VocabularyEntry('hour', 'hodina (60 minut)', 'Dny a čas', 21),
  VocabularyEntry(
    'easy',
    'snadný',
    'Popis lidí a věcí',
    21,
    alternatives: ['simple'],
  ),
  VocabularyEntry('make', 'vyrobit', 'Pokyny a slovesa', 21),
  VocabularyEntry('move', 'pohnout / přemístit', 'Pokyny a slovesa', 21),
  VocabularyEntry('stop', 'zastavit', 'Pokyny a slovesa', 21),
  VocabularyEntry(
    'tell the time',
    'určit čas podle hodin',
    'Kolik je hodin?',
    21,
  ),
  VocabularyEntry(
    'Hi!',
    'Ahoj! (při setkání)',
    'Krátké fráze',
    4,
    alternatives: ['Hello!', 'Hey!'],
  ),
  VocabularyEntry(
    'Goodbye!',
    'Na shledanou!',
    'Krátké fráze',
    4,
    alternatives: ['Bye!', 'Bye-bye!'],
  ),
  VocabularyEntry(
    'Have a good day!',
    'Hezký den!',
    'Krátké fráze',
    4,
    alternatives: ['Have a nice day!'],
  ),
  VocabularyEntry(
    'Wait a minute!',
    'Počkej chvilku!',
    'Krátké fráze',
    4,
    alternatives: ['Wait a moment!'],
  ),
  VocabularyEntry(
    "What's that?",
    'Co je to tam?',
    'Krátké fráze',
    4,
    alternatives: ['What is that?'],
  ),
  VocabularyEntry(
    'What colour is it?',
    'Jakou to má barvu?',
    'Krátké fráze',
    5,
    alternatives: ['What color is it?'],
  ),
  VocabularyEntry(
    'Sorry!',
    'Promiň!',
    'Krátké fráze',
    6,
    alternatives: ["I'm sorry!", 'I am sorry!'],
  ),
  VocabularyEntry(
    "What's your name?",
    'Jak se jmenuješ?',
    'Krátké fráze',
    6,
    alternatives: ['What is your name?'],
  ),
  VocabularyEntry('Where are you from?', 'Odkud jsi?', 'Krátké fráze', 6),
  VocabularyEntry('How old are you?', 'Kolik ti je let?', 'Krátké fráze', 6),
  VocabularyEntry('Me too!', 'Já také!', 'Krátké fráze', 6),
  VocabularyEntry('Excuse me.', 'Promiňte. (oslovení)', 'Krátké fráze', 6),
  VocabularyEntry('please', 'prosím (při žádosti)', 'Krátké fráze', 6),
  VocabularyEntry(
    'of course',
    'samozřejmě',
    'Krátké fráze',
    6,
    alternatives: ['certainly'],
  ),
  VocabularyEntry(
    'Here you are.',
    'Tady máš.',
    'Krátké fráze',
    6,
    alternatives: ['Here you go.'],
  ),
  VocabularyEntry('See you soon!', 'Brzy na viděnou!', 'Krátké fráze', 8),
  VocabularyEntry('Why not?', 'Proč ne?', 'Krátké fráze', 8),
  VocabularyEntry('Really?', 'Opravdu?', 'Krátké fráze', 8),
  VocabularyEntry(
    'Can you say that again, please?',
    'Můžeš to prosím říct znovu?',
    'Krátké fráze',
    9,
    alternatives: [
      'Can you repeat that, please?',
      'Could you say that again, please?',
      'Could you repeat that, please?',
    ],
  ),
  VocabularyEntry(
    'Me neither!',
    'Já také ne!',
    'Krátké fráze',
    10,
    alternatives: ['Neither do I!', 'Neither am I!', 'Neither can I!'],
  ),
  VocabularyEntry(
    'Thanks!',
    'Děkuji!',
    'Krátké fráze',
    14,
    alternatives: ['Thank you!'],
  ),
  VocabularyEntry(
    'Hurray!',
    'Hurá!',
    'Krátké fráze',
    14,
    alternatives: ['Hooray!', 'Hurrah!'],
  ),
  VocabularyEntry('Come on!', 'Pojď! / No tak!', 'Krátké fráze', 14),
  VocabularyEntry(
    "Don't touch!",
    'Nedotýkej se!',
    'Krátké fráze',
    14,
    alternatives: ['Do not touch!'],
  ),
  VocabularyEntry(
    "When's your birthday?",
    'Kdy máš narozeniny?',
    'Krátké fráze',
    15,
    alternatives: ['When is your birthday?'],
  ),
  VocabularyEntry('Hurry up!', 'Pospěš si!', 'Krátké fráze', 16),
  VocabularyEntry(
    'What time is it?',
    'Kolik je hodin?',
    'Krátké fráze',
    16,
    alternatives: ["What's the time?", 'What is the time?'],
  ),
  VocabularyEntry(
    "What's the matter?",
    'Co se děje?',
    'Krátké fráze',
    16,
    alternatives: ['What is the matter?', "What's wrong?", 'What is wrong?'],
  ),
];
